"""Deterministic offline candle recipes for Scanner fast-path regression tests.

The corpus deliberately contains no market, MT5, news, or AI-provider inputs.
Every recipe can be regenerated byte-for-byte from its JSON descriptor.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from typing import Any

from core.market_models import Candle
from core.risk_engine import AnalysisInput


_START = datetime(2026, 1, 1, tzinfo=timezone.utc)


def make_request(
    case: dict[str, Any],
    request_config: dict[str, Any] | None = None,
) -> AnalysisInput:
    """Build the fixed AnalysisInput shared by corpus cases."""

    config = request_config or {}
    return AnalysisInput(
        symbol=str(case.get("symbol", "EUR/USD")),
        broker_symbol=str(config.get("broker_symbol", "EURUSDm")),
        account_balance=float(config.get("account_balance", 10_000.0)),
        risk_percent=float(config.get("risk_percent", 1.0)),
        account_currency=str(config.get("account_currency", "USD")),
        lot_step=float(config.get("lot_step", 0.01)),
        minimum_lot=float(config.get("minimum_lot", 0.01)),
        contract_size_override=float(config.get("contract_size_override", 100_000.0)),
        timezone_name=str(config.get("timezone_name", "Asia/Ho_Chi_Minh")),
    )


def make_candles(case: dict[str, Any]) -> dict[str, list[Candle]]:
    """Regenerate all D1/H4/H1/M15 candles for one corpus descriptor."""

    recipe = str(case["recipe"])
    base_price = float(case.get("base_price", 1.1000))
    return {
        "D1": _trend(80, base_price, 0.00004, 1440),
        "H4": _for_recipe(recipe if recipe.startswith("h4_") else "plain", base_price, 240),
        "H1": _for_recipe(recipe.removeprefix("h4_"), base_price, 60),
        "M15": _trend(120, base_price, 0.00001, 15),
    }


def _for_recipe(recipe: str, base_price: float, minutes: int) -> list[Candle]:
    if recipe == "plain":
        return _trend(100, base_price, 0.00001, minutes)
    if recipe in {"bullish_fvg", "buy_setup"}:
        return _bullish_impulse(base_price, minutes, broken=False)
    if recipe == "broken_bullish_fvg":
        return _bullish_impulse(base_price, minutes, broken=True)
    if recipe in {"bearish_order_block", "sell_setup"}:
        return _bearish_impulse(base_price, minutes, broken=False)
    raise ValueError(f"Unknown scanner fast-path recipe: {recipe}")


def _trend(n: int, start: float, step: float, minutes: int) -> list[Candle]:
    """Overlapping trend candles: stable technical data without raw SMC zones."""

    candles: list[Candle] = []
    timestamp = _START
    price = start
    wick = abs(step) * 1.8 + 0.00003
    for index in range(n):
        open_price = price
        close_price = price + step
        candles.append(
            Candle(
                time=timestamp,
                open=round(open_price, 6),
                high=round(max(open_price, close_price) + wick, 6),
                low=round(min(open_price, close_price) - wick, 6),
                close=round(close_price, 6),
                volume=float(1_000 + index),
            )
        )
        timestamp += timedelta(minutes=minutes)
        price = close_price
    return candles


def _bullish_impulse(
    base_price: float,
    minutes: int,
    *,
    broken: bool,
) -> list[Candle]:
    """Create a latest bullish OB/FVG; optionally invalidate it afterwards."""

    candles = _trend(95, base_price, 0.000003, minutes)
    timestamp = candles[-1].time + timedelta(minutes=minutes)
    anchor = candles[-1].close
    candles.extend([
        Candle(timestamp, anchor, anchor + 0.00003, anchor - 0.00009, anchor - 0.00006, 1_500),
        Candle(
            timestamp + timedelta(minutes=minutes),
            anchor - 0.00006,
            anchor + 0.00036,
            anchor - 0.00008,
            anchor + 0.00032,
            1_600,
        ),
        Candle(
            timestamp + timedelta(minutes=minutes * 2),
            anchor + 0.00031,
            anchor + 0.00042,
            anchor + 0.00024,
            anchor + 0.00038,
            1_700,
        ),
    ])
    if broken:
        candles.append(
            Candle(
                timestamp + timedelta(minutes=minutes * 3),
                anchor + 0.00037,
                anchor + 0.00038,
                anchor - 0.00018,
                anchor - 0.00014,
                1_800,
            )
        )
    return candles


def _bearish_impulse(
    base_price: float,
    minutes: int,
    *,
    broken: bool,
) -> list[Candle]:
    """Create a latest bearish OB/FVG; ``broken`` is kept for recipe symmetry."""

    del broken
    candles = _trend(95, base_price, 0.000003, minutes)
    timestamp = candles[-1].time + timedelta(minutes=minutes)
    anchor = candles[-1].close
    candles.extend([
        Candle(timestamp, anchor, anchor + 0.00009, anchor - 0.00003, anchor + 0.00006, 1_500),
        Candle(
            timestamp + timedelta(minutes=minutes),
            anchor + 0.00006,
            anchor + 0.00008,
            anchor - 0.00036,
            anchor - 0.00032,
            1_600,
        ),
        Candle(
            timestamp + timedelta(minutes=minutes * 2),
            anchor - 0.00031,
            anchor - 0.00024,
            anchor - 0.00042,
            anchor - 0.00038,
            1_700,
        ),
    ])
    return candles
