from __future__ import annotations

from enum import Enum


class SDReasonCode(str, Enum):
    DATA_SYMBOL_UNRESOLVED = "DATA_SYMBOL_UNRESOLVED"
    DATA_MISSING_TIMEFRAME = "DATA_MISSING_TIMEFRAME"
    DATA_INVALID_OHLC = "DATA_INVALID_OHLC"
    DATA_TIMESTAMP_INVALID = "DATA_TIMESTAMP_INVALID"
    DATA_ATR_INSUFFICIENT = "DATA_ATR_INSUFFICIENT"
    DATA_TICK_SIZE_MISSING = "DATA_TICK_SIZE_MISSING"
    DATA_QUOTE_MISSING = "DATA_QUOTE_MISSING"
    DATA_SPREAD_INVALID = "DATA_SPREAD_INVALID"
    DATA_STALE = "DATA_STALE"
    DATA_SESSION_POLICY_MISSING = "DATA_SESSION_POLICY_MISSING"
    DATA_SESSION_GAP = "DATA_SESSION_GAP"
    DATA_CANDLE_BOUNDARY_UNRESOLVED = "DATA_CANDLE_BOUNDARY_UNRESOLVED"
    AMBIGUOUS_ARRIVAL = "AMBIGUOUS_ARRIVAL"
    INVALID_ARRIVAL = "INVALID_ARRIVAL"
    INVALID_BASE = "INVALID_BASE"
    INVALID_DEPARTURE = "INVALID_DEPARTURE"
    ZONE_TOO_WIDE = "ZONE_TOO_WIDE"
    ZONE_TOO_NARROW = "ZONE_TOO_NARROW"
    DUPLICATE_ZONE = "DUPLICATE_ZONE"
    D1_BIAS_UNALIGNED = "D1_BIAS_UNALIGNED"
    LOCATION_UNALIGNED = "LOCATION_UNALIGNED"
    H4_PARENT_MISSING = "H4_PARENT_MISSING"
    H4_PARENT_BROKEN = "H4_PARENT_BROKEN"
    H4_PARENT_EXPIRED = "H4_PARENT_EXPIRED"
    DIRECTION_CONFLICT = "DIRECTION_CONFLICT"
    ENTRY_NOT_REACHED = "ENTRY_NOT_REACHED"
    PROTECTIVE_ZONE_BROKEN = "PROTECTIVE_ZONE_BROKEN"
    PROTECTIVE_ZONE_EXPIRED = "PROTECTIVE_ZONE_EXPIRED"
    FIRST_RETEST_COMPLETED = "FIRST_RETEST_COMPLETED"
    M15_CONFIRMATION_REQUIRED = "M15_CONFIRMATION_REQUIRED"
    M15_CONFIRMATION_TIMEOUT = "M15_CONFIRMATION_TIMEOUT"
    M15_REJECTION = "M15_REJECTION"
    M15_ENGULFING = "M15_ENGULFING"
    M15_MICRO_BOS = "M15_MICRO_BOS"
    QUALITY_BELOW_MIN = "QUALITY_BELOW_MIN"
    OPPOSING_ZONE_MISSING = "OPPOSING_ZONE_MISSING"
    INVALID_TRADE_GEOMETRY = "INVALID_TRADE_GEOMETRY"
    RR_BELOW_MIN = "RR_BELOW_MIN"
    ENTRY_INSIDE_OPPOSING_ZONE = "ENTRY_INSIDE_OPPOSING_ZONE"
    STATE_SNAPSHOT_INVALID = "STATE_SNAPSHOT_INVALID"
    RULES_VERSION_MISMATCH = "RULES_VERSION_MISMATCH"
    ZONE_NOT_RECONSTRUCTED = "ZONE_NOT_RECONSTRUCTED"
    FULL_ANALYSIS_PENDING = "FULL_ANALYSIS_PENDING"
    STATE_RESTORED = "STATE_RESTORED"
    READY = "READY"


_GROUPS = {
    "DATA_": 0, "INVALID_": 1, "AMBIGUOUS_": 1, "ZONE_": 1,
    "DUPLICATE_": 1, "D1_": 2, "LOCATION_": 2, "H4_": 2,
    "DIRECTION_": 2, "ENTRY_": 3, "PROTECTIVE_": 3,
    "FIRST_": 3, "M15_": 4, "QUALITY_": 5, "OPPOSING_": 5,
    "RR_": 5, "STATE_": 6, "RULES_": 6, "FULL_": 6, "READY": 7,
}


def sort_reason_codes(codes: tuple[SDReasonCode, ...] | list[SDReasonCode]) -> tuple[SDReasonCode, ...]:
    def key(code: SDReasonCode) -> tuple[int, str]:
        name = code.value
        group = next((rank for prefix, rank in _GROUPS.items() if name.startswith(prefix)), 99)
        return group, name

    return tuple(sorted(set(codes), key=key))
